#include <stdio.h>
#include <stdint.h>

#define MAX_K1 500000

/*
from output.txt generated by day14_2.exe, we observed a horizontal and a vertical pattern. 
- The horizontal pattern appears on frames f1(n) = 84 + 101 * n
- The vertical pattern appears on frames f2(n) = 33 + 103 * n

In this program, I'm looking for a couple (k1, k2) in N² (two integers)

The first couple is (77,76) where f1(n1) = f2(n2) = 7861.

The christmas tree appears the first time 7861 seconds after the beginning. 
*/


int main(){

    uint64_t tmp, k1;
    for (uint64_t k2 = 0 ; k2 < MAX_K1 ; k2++){
        tmp = 51 + 101 * k2;
        if ((tmp % 103) == 0){
            k1 = tmp / 103;
            printf("\n%lld : k1 = %lld, k2 = %lld", (33 + 103 * k1), k1, k2);
            getchar();
        }
    }
}